### PR TITLE
Added method to check if a local cache of credentials exists. 

### PR DESCRIPTION
**Pull request by LarsBuur**
Added method for checking if local cache exists with credentials. If it exists then the cached credentials are used. Once expired normal operation is resumed.

### CODE REVIEW

**Comment by jonknapp** [comment]
Thanks for the PR! Caching has been a [topic](#2) I've tried to avoid, mostly so I didn't have to determine if there are edge cases creating/storing files in different operating systems with different AWS configurations/env setups/etc.

I'll make a note to look at this a bit more in depth in the future and come back with feedback, if any.

**Comment by LarsBuur** [comment]
Understood. I made the changes because I had to enter a new mfa key too many times... 

Please note that I deliberately did not implement writing to the .aws/cli/cache - but only see if it´s there. 

Therefore the .aws/cli/cache will not be there if you only use aws-auth-helper. 

The change requires you to use the normal aws cli and use a command and profile that required a mfa key e.g. 
```
aws s3 ls --profile whatever
```
Afterward the .aws/cli/cache file should exist and be valid for 1 hour and thus used. Once expired the mfa key will be required again.

**Comment by jonknapp** [comment]
If you're already using the aws cli, are you using the built in ability to use MFA and authenticate with a role?

In my `~/.aws/config` I have:

```
[profile default]
mfa_serial=arn:aws:iam::123456789:mfa/jon
output=json
region=us-east-1
role_arn=arn:aws:iam::123456789:role/CustomRoleIWantToAssume
source_profile=default
```

and in `~/.aws/credentials` I have:

```
[default]
aws_access_key_id=xxxxxxxx
aws_secret_access_key=xxxxxxxx
```

**Comment by LarsBuur** [comment]
Yes - my config and profile look exactly the same. 

If you look in ~/.aws/config/cli/cache directory you will see your cached credentials which are the ones that I am reusing if valid.

**Comment by jonknapp** [comment]
Thanks for the pull request Lars, but I'm still a bit uneasy about bringing this in.

For your specific use case, if you stored/re-used the returned env vars after the first `aws-auth-helper` call I believe you'd be set. If you'd like to describe the setup/situation you encountered maybe I can understand the use case a bit more. In my mind, a small bash script that potentially leveraged `jq` may fit what you need but I don't understand your situation well enough.

**Pull request closed without merging**
